from __future__ import annotations

from decimal import Decimal, InvalidOperation
from typing import Any, Iterable

from axiz.pe.sql_agent.models.contracts import (
    SqlChangeRequest,
    SqlChangeType,
    SqlFeedbackApplication,
    SqlFeedbackPlan,
    SqlFeedbackStrategy,
    SqlTemporalScope,
    TimeWindowContext,
)


class SqlFeedbackApplier:
    """Apply safe structural portions of a semantic HITL feedback plan to SQL AST.

    Semantic changes are still regenerated by the SQL agent. This tool then enforces structural
    postconditions that can be applied without guessing business meaning: limits, simple filters
    and ordering. More complex requests are marked as deferred and verified by the compliance
    stage against the regenerated SQL.
    """

    _DETERMINISTIC_TYPES = {
        SqlChangeType.SET_LIMIT,
        SqlChangeType.ADD_FILTER,
        SqlChangeType.REMOVE_FILTER,
        SqlChangeType.REPLACE_FILTER,
        SqlChangeType.CHANGE_TIME_WINDOW,
        SqlChangeType.CHANGE_ORDER,
    }

    def __init__(self, dialect: str, max_rows: int) -> None:
        self.dialect = dialect
        self.max_rows = max_rows

    def apply(
        self,
        sql: str,
        feedback_or_plan: str | SqlFeedbackPlan | dict[str, Any] | None,
        *,
        previous_sql: str | None = None,
    ) -> SqlFeedbackApplication:
        plan = self._coerce_plan(feedback_or_plan)
        if not plan or not plan.changes:
            return SqlFeedbackApplication(sql=sql.strip().rstrip(";"))

        import sqlglot

        try:
            tree = sqlglot.parse_one(sql, read=self.dialect)
        except sqlglot.errors.ParseError as exc:
            return SqlFeedbackApplication(
                sql=sql.strip().rstrip(";"),
                failed_changes=[change.change_id for change in plan.changes],
                warnings=[f"No se pudo aplicar el feedback sobre el AST: {exc}"],
            )

        application = SqlFeedbackApplication(sql=sql.strip().rstrip(";"))
        if previous_sql:
            try:
                previous_tree = sqlglot.parse_one(previous_sql, read=self.dialect)
                self._preserve_unrequested_invariants(
                    previous_tree,
                    tree,
                    plan,
                    application,
                )
            except sqlglot.errors.ParseError as exc:
                application.warnings.append(
                    f"No se pudo preservar el contrato SQL anterior: {exc}"
                )
        for change in plan.changes:
            if (
                change.change_type not in self._DETERMINISTIC_TYPES
                or not change.deterministic_candidate
            ):
                application.deferred_changes.append(change.change_id)
                continue
            try:
                changed = self._apply_change(tree, change, application)
            except (TypeError, ValueError) as exc:
                application.failed_changes.append(change.change_id)
                application.warnings.append(
                    f"No se pudo aplicar {change.change_id} de forma determinística: {exc}"
                )
                continue
            if changed:
                application.applied_changes.append(change.change_id)
                application.changed = True
            else:
                # The regenerated SQL may already contain the requested state. Compliance will
                # verify it, so this is not considered a failure.
                application.deferred_changes.append(change.change_id)

        application.sql = tree.sql(dialect=self.dialect, pretty=True)
        return application

    def _preserve_unrequested_invariants(
        self,
        previous_tree: Any,
        revised_tree: Any,
        plan: SqlFeedbackPlan,
        application: SqlFeedbackApplication,
    ) -> None:
        """Restore clauses that the user did not request to modify.

        This is intentionally deterministic. A semantic follow-up may regenerate SQL, but it
        must not reset a previously approved LIMIT, ORDER BY, filter, grouping or projection just
        because the generator used a default/example query.
        """
        from sqlglot import exp

        change_types = {change.change_type for change in plan.changes}
        if SqlChangeType.SEMANTIC_REGENERATION in change_types:
            return

        previous_select = self._root_select(previous_tree)
        revised_select = self._root_select(revised_tree)

        if SqlChangeType.SET_LIMIT not in change_types:
            self._preserve_arg(
                previous_tree,
                revised_tree,
                "limit",
                "limit",
                application,
            )

        if SqlChangeType.CHANGE_ORDER not in change_types:
            if self._previous_order_is_compatible(previous_select, revised_select):
                self._preserve_arg(
                    previous_select,
                    revised_select,
                    "order",
                    "ordering",
                    application,
                )
            else:
                application.preserved_invariants.append("ordering_dependency_reconciled")

        filter_changes = {
            SqlChangeType.ADD_FILTER,
            SqlChangeType.REMOVE_FILTER,
            SqlChangeType.REPLACE_FILTER,
            SqlChangeType.CHANGE_TIME_WINDOW,
        }
        if not (change_types & filter_changes):
            self._preserve_arg(
                previous_select,
                revised_select,
                "where",
                "filters",
                application,
            )

        dimension_changes = {
            SqlChangeType.ADD_DIMENSION,
            SqlChangeType.REMOVE_DIMENSION,
            SqlChangeType.CHANGE_GROUPING,
        }
        comparative_temporal_changes = [
            change
            for change in plan.changes
            if change.change_type == SqlChangeType.CHANGE_TIME_WINDOW
            and change.time_window_scope != SqlTemporalScope.OVERALL_WINDOW
        ]
        temporal_series_change = any(
            change.time_window_scope == SqlTemporalScope.COMPARISON_SERIES
            for change in comparative_temporal_changes
        )
        if not (change_types & dimension_changes) and not temporal_series_change:
            self._preserve_arg(
                previous_select,
                revised_select,
                "group",
                "grouping",
                application,
            )
            self._preserve_arg(
                previous_select,
                revised_select,
                "having",
                "having",
                application,
            )

        semantic_shape_changes = dimension_changes | {
            SqlChangeType.ADD_METRIC,
            SqlChangeType.REMOVE_METRIC,
            SqlChangeType.REPLACE_METRIC,
            SqlChangeType.REPLACE_SOURCE,
        }
        if not (change_types & semantic_shape_changes) and not comparative_temporal_changes:
            previous_expressions = previous_select.args.get("expressions") or []
            revised_expressions = revised_select.args.get("expressions") or []
            if self._sql_list(previous_expressions) != self._sql_list(revised_expressions):
                revised_select.set(
                    "expressions",
                    [expression.copy() for expression in previous_expressions],
                )
                application.preserved_invariants.append("projection")

            for key, label in (("from_", "sources"), ("joins", "joins")):
                self._preserve_arg(
                    previous_select,
                    revised_select,
                    key,
                    label,
                    application,
                )
        elif comparative_temporal_changes:
            # Temporal comparison changes may alter projected period expressions, but they do not
            # authorize source substitution or unrelated joins.
            for key, label in (("from_", "sources"), ("joins", "joins")):
                self._preserve_arg(
                    previous_select,
                    revised_select,
                    key,
                    label,
                    application,
                )

        # Preserve DISTINCT unless the analytical shape explicitly changed.
        if not (change_types & semantic_shape_changes) and not temporal_series_change:
            self._preserve_arg(
                previous_select,
                revised_select,
                "distinct",
                "distinct",
                application,
            )

    def _preserve_arg(
        self,
        previous: Any,
        revised: Any,
        key: str,
        label: str,
        application: SqlFeedbackApplication,
    ) -> None:
        previous_value = previous.args.get(key)
        revised_value = revised.args.get(key)
        if self._sql_value(previous_value) == self._sql_value(revised_value):
            return
        if isinstance(previous_value, list):
            revised.set(key, [value.copy() for value in previous_value])
        elif previous_value is None:
            revised.set(key, None)
        else:
            revised.set(key, previous_value.copy())
        application.preserved_invariants.append(label)

    def _sql_value(self, value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, list):
            return "|".join(self._sql_list(value))
        return value.sql(dialect=self.dialect).strip().lower()

    def _sql_list(self, values: Iterable[Any]) -> list[str]:
        return [value.sql(dialect=self.dialect).strip().lower() for value in values]

    def _previous_order_is_compatible(self, previous_select: Any, revised_select: Any) -> bool:
        """Return False when preserving ORDER BY would reintroduce a removed projection member.

        Semantic feedback may replace a measure even when the user's wording sounds like a filter
        change. In that case the revised SQL must be allowed to update dependent aliases, HAVING and
        ordering. Preserving an obsolete alias would create an invalid candidate such as ordering by
        ``processed_amount_pen`` after the projection changed to ``declined_transaction_count``.
        """
        from sqlglot import exp

        previous_order = previous_select.args.get("order")
        if previous_order is None:
            return True
        previous_aliases = {
            self._identifier_key(str(item.alias))
            for item in previous_select.expressions
            if item.alias
        }
        revised_aliases = {
            self._identifier_key(str(item.alias))
            for item in revised_select.expressions
            if item.alias
        }
        removed_aliases = previous_aliases - revised_aliases
        if not removed_aliases:
            return True
        referenced = {
            self._identifier_key(column.name)
            for ordered in previous_order.expressions
            for column in ordered.find_all(exp.Column)
            if column.name
        }
        return not bool(removed_aliases & referenced)

    def reconcile_interpretation(
        self,
        interpretation: str,
        application: SqlFeedbackApplication,
    ) -> str:
        """Append verified structural changes without parsing natural language text."""
        updates: list[str] = []
        if application.applied_time_window_months is not None:
            months = application.applied_time_window_months
            updates.append(
                "usar el último mes calendario completamente cerrado"
                if months == 1
                else f"usar los últimos {months} meses calendario completamente cerrados"
            )
        if application.applied_time_window_days is not None:
            days = application.applied_time_window_days
            updates.append(
                "usar el último día calendario completo"
                if days == 1
                else f"usar los últimos {days} días calendario completos"
            )
        if application.applied_limit is not None:
            updates.append(f"devolver como máximo {application.applied_limit} resultados")
        if not updates:
            return interpretation
        base = interpretation.rstrip().rstrip(".")
        return base + ". Ajustes verificados: " + "; ".join(updates) + "."

    def reconcile_time_window(
        self,
        time_window: TimeWindowContext | None,
        application: SqlFeedbackApplication,
    ) -> TimeWindowContext | None:
        months = application.applied_time_window_months
        days = application.applied_time_window_days
        if months is None and days is None:
            return time_window
        if months is not None and days is not None:
            raise ValueError("Una revisión temporal no puede aplicar meses y días simultáneamente")

        if months is not None:
            label = (
                "Último mes calendario completamente cerrado"
                if months == 1
                else f"Últimos {months} meses calendario completamente cerrados"
            )
            start_expression = f"inicio_mes_actual - {months} mes{'es' if months != 1 else ''}"
            grain = "month"
        else:
            assert days is not None
            label = (
                "Último día calendario completo"
                if days == 1
                else f"Últimos {days} días calendario completos"
            )
            start_expression = f"fecha_actual - {days} día{'s' if days != 1 else ''}"
            grain = "day"

        return TimeWindowContext(
            label=label,
            start_expression=start_expression,
            end_expression=time_window.end_expression if time_window else None,
            grain=time_window.grain if time_window and time_window.grain else grain,
            closed_period=True,
        )

    def reconcile_filters(
        self,
        filters: list[dict[str, Any]],
        plan: SqlFeedbackPlan | None,
    ) -> list[dict[str, Any]]:
        if not plan:
            return list(filters)
        current = [dict(item) for item in filters]
        for change in plan.changes:
            target = self._identifier_key(change.target or "")
            if change.change_type == SqlChangeType.REMOVE_FILTER:
                current = [
                    item for item in current
                    if self._identifier_key(str(item.get("field", ""))) != target
                ]
            elif change.change_type == SqlChangeType.REPLACE_FILTER:
                previous = self._identifier_key(change.previous_target or change.target or "")
                current = [
                    item for item in current
                    if self._identifier_key(str(item.get("field", ""))) != previous
                ]
                if change.target:
                    current.append(self._filter_contract(change))
            elif change.change_type == SqlChangeType.ADD_FILTER and change.target:
                candidate = self._filter_contract(change)
                if candidate not in current:
                    current.append(candidate)
        return current

    @staticmethod
    def _filter_contract(change: SqlChangeRequest) -> dict[str, Any]:
        value = change.value
        if change.values:
            value = ", ".join(change.values)
        return {
            "field": change.target or "",
            "operator": change.operator or "=",
            "value": value or "",
            "source": "human_feedback",
        }

    def _apply_change(
        self,
        tree: Any,
        change: SqlChangeRequest,
        application: SqlFeedbackApplication,
    ) -> bool:
        if change.change_type == SqlChangeType.SET_LIMIT:
            return self._set_limit(tree, change, application)
        if change.change_type == SqlChangeType.ADD_FILTER:
            return self._add_filter(tree, change)
        if change.change_type == SqlChangeType.REMOVE_FILTER:
            return self._remove_filter(tree, change)
        if change.change_type == SqlChangeType.REPLACE_FILTER:
            removed = self._remove_filter(tree, change, previous=True)
            added = self._add_filter(tree, change)
            return removed or added
        if change.change_type == SqlChangeType.CHANGE_TIME_WINDOW:
            return self._change_time_window(tree, change, application)
        if change.change_type == SqlChangeType.CHANGE_ORDER:
            return self._change_order(tree, change)
        return False

    def _set_limit(
        self,
        tree: Any,
        change: SqlChangeRequest,
        application: SqlFeedbackApplication,
    ) -> bool:
        from sqlglot import exp

        requested = change.limit
        if requested is None and change.value:
            requested = self._parse_positive_int(change.value)
        if requested is None:
            raise ValueError("set_limit requiere limit o value numérico")
        applied = min(requested, self.max_rows)
        previous = self._read_limit(tree)
        tree.set("limit", exp.Limit(expression=exp.Literal.number(applied)))
        application.requested_limit = requested
        application.applied_limit = applied
        application.previous_limit = previous
        if requested > self.max_rows:
            application.warnings.append(
                f"El límite solicitado ({requested}) supera MAX_RESULT_ROWS={self.max_rows}; "
                f"se aplicó {applied}."
            )
        return previous != applied

    def _change_time_window(
        self,
        tree: Any,
        change: SqlChangeRequest,
        application: SqlFeedbackApplication,
    ) -> bool:
        if change.time_window_scope != SqlTemporalScope.OVERALL_WINDOW:
            raise ValueError(
                "Los cambios temporales comparativos requieren regeneración semántica"
            )
        month_values = (
            change.time_window_months,
            change.time_window_delta_months,
        )
        day_values = (
            change.time_window_days,
            change.time_window_delta_days,
        )
        has_month_request = any(value is not None for value in month_values)
        has_day_request = any(value is not None for value in day_values)
        if has_month_request and has_day_request:
            raise ValueError(
                "change_time_window no puede mezclar ajustes en meses y días"
            )
        if not has_month_request and not has_day_request:
            raise ValueError(
                "change_time_window requiere un valor o delta explícito en meses o días"
            )

        if has_day_request:
            candidate = self._rolling_day_window_candidate(tree, dialect=self.dialect)
            if candidate is None:
                raise ValueError(
                    "change_time_window requiere una única ventana diaria cerrada verificable"
                )
            delta_node, previous_days, delta_kind = candidate
            requested_days = change.time_window_days
            delta = change.time_window_delta_days
            if requested_days is not None and delta is not None:
                raise ValueError(
                    "change_time_window no puede definir días absolutos y delta simultáneamente"
                )
            if requested_days is None:
                assert delta is not None
                requested_days = previous_days + delta
            if requested_days < 1 or requested_days > 3650:
                raise ValueError("La ventana diaria resultante debe estar entre 1 y 3650 días")
            self._set_day_delta(delta_node, requested_days, delta_kind)
            application.requested_time_window_delta_days = delta
            application.previous_time_window_days = previous_days
            application.applied_time_window_days = requested_days
            return previous_days != requested_days

        candidate = self._closed_month_window_candidate(tree, dialect=self.dialect)
        if candidate is None:
            raise ValueError(
                "change_time_window requiere una única ventana mensual cerrada verificable"
            )
        interval, previous_months = candidate
        requested_months = change.time_window_months
        delta = change.time_window_delta_months
        if requested_months is not None and delta is not None:
            raise ValueError(
                "change_time_window no puede definir meses absolutos y delta simultáneamente"
            )
        if requested_months is None:
            assert delta is not None
            requested_months = previous_months + delta
        if requested_months < 1 or requested_months > 120:
            raise ValueError("La ventana mensual resultante debe estar entre 1 y 120 meses")

        self._set_interval_months(interval, requested_months)
        application.requested_time_window_delta_months = delta
        application.previous_time_window_months = previous_months
        application.applied_time_window_months = requested_months
        return previous_months != requested_months

    @classmethod
    def rolling_day_window_days(
        cls,
        sql: str,
        *,
        dialect: str = "postgres",
    ) -> int | None:
        try:
            import sqlglot
        except ImportError:
            return None
        try:
            tree = sqlglot.parse_one(sql, read=dialect)
        except sqlglot.errors.ParseError:
            return None
        candidate = cls._rolling_day_window_candidate(tree, dialect=dialect)
        return candidate[1] if candidate else None

    @classmethod
    def _rolling_day_window_candidate(
        cls,
        tree: Any,
        *,
        dialect: str,
    ) -> tuple[Any, int, str] | None:
        from sqlglot import exp

        try:
            select = cls._root_select(tree)
        except ValueError:
            return None
        where = select.args.get("where")
        if where is None:
            return None
        terms = cls._flatten_and(where.this)
        upper_bounds: dict[str, set[str]] = {}
        candidates: list[tuple[Any, int, str, str, str]] = []

        for term in terms:
            if isinstance(term, (exp.LT, exp.LTE)):
                column = term.this if isinstance(term.this, exp.Column) else next(
                    term.this.find_all(exp.Column), None
                )
                if column is None:
                    continue
                key = cls._identifier_key(column.name)
                upper_bounds.setdefault(key, set()).add(
                    cls._normalized_expression_sql(term.expression, dialect)
                )
                continue
            if not isinstance(term, (exp.GT, exp.GTE)):
                continue
            column = term.this if isinstance(term.this, exp.Column) else next(
                term.this.find_all(exp.Column), None
            )
            if column is None:
                continue
            parsed = cls._extract_day_delta(term.expression, dialect=dialect)
            if parsed is None:
                continue
            node, days, kind, base_sql = parsed
            candidates.append(
                (node, days, kind, cls._identifier_key(column.name), base_sql)
            )

        valid = [
            (node, days, kind)
            for node, days, kind, column, base_sql in candidates
            if base_sql in upper_bounds.get(column, set())
        ]
        if len(valid) != 1:
            return None
        return valid[0]

    @classmethod
    def _extract_day_delta(
        cls,
        expression: Any,
        *,
        dialect: str,
    ) -> tuple[Any, int, str, str] | None:
        from sqlglot import exp

        candidate = expression
        while isinstance(candidate, (exp.Cast, exp.Paren)):
            candidate = candidate.this
        if not isinstance(candidate, exp.Sub):
            return None
        base = candidate.this
        delta = candidate.expression
        if isinstance(delta, exp.Literal) and delta.is_int:
            days = int(delta.this)
            if days < 1:
                return None
            return (
                delta,
                days,
                "literal",
                cls._normalized_expression_sql(base, dialect),
            )
        if isinstance(delta, exp.Interval):
            days = cls._interval_days(delta)
            if days is None or days < 1:
                return None
            return (
                delta,
                days,
                "interval",
                cls._normalized_expression_sql(base, dialect),
            )
        return None

    @staticmethod
    def _normalized_expression_sql(expression: Any, dialect: str) -> str:
        return " ".join(expression.sql(dialect=dialect).upper().split())

    @staticmethod
    def _interval_days(interval: Any) -> int | None:
        unit_expression = interval.args.get("unit")
        unit = str(
            getattr(unit_expression, "name", "")
            or getattr(unit_expression, "this", "")
            or ""
        ).upper()
        raw = str(getattr(interval.this, "this", interval.this) or "").strip()
        if unit:
            if unit not in {"DAY", "DAYS"}:
                return None
            try:
                return int(raw)
            except ValueError:
                return None
        parts = raw.upper().split()
        if len(parts) != 2 or parts[1].rstrip("S") != "DAY":
            return None
        try:
            return int(parts[0])
        except ValueError:
            return None

    @staticmethod
    def _set_day_delta(node: Any, days: int, kind: str) -> None:
        from sqlglot import exp

        if kind == "literal":
            node.set("this", str(days))
            return
        if kind != "interval":
            raise ValueError(f"Tipo de delta diario no soportado: {kind}")
        unit_expression = node.args.get("unit")
        if unit_expression is not None:
            node.set("this", exp.Literal.string(str(days)))
        else:
            unit = "DAY" if days == 1 else "DAYS"
            node.set("this", exp.Literal.string(f"{days} {unit}"))

    @classmethod
    def closed_month_window_months(
        cls,
        sql: str,
        *,
        dialect: str = "postgres",
    ) -> int | None:
        """Return the size of a single closed-month window, otherwise ``None``.

        SQLGlot is authoritative. If it is unavailable or cannot parse the statement, the method
        returns ``None`` and the caller must use semantic regeneration or clarification.
        """
        try:
            import sqlglot
        except ImportError:
            return None
        try:
            tree = sqlglot.parse_one(sql, read=dialect)
        except sqlglot.errors.ParseError:
            return None
        candidate = cls._closed_month_window_candidate(tree, dialect=dialect)
        return candidate[1] if candidate else None

    @classmethod
    def _closed_month_window_candidate(
        cls,
        tree: Any,
        *,
        dialect: str,
    ) -> tuple[Any, int] | None:
        from sqlglot import exp

        try:
            select = cls._root_select(tree)
        except ValueError:
            return None
        where = select.args.get("where")
        if where is None:
            return None
        terms = cls._flatten_and(where.this)
        candidates: list[tuple[Any, int, str]] = []
        upper_bounds: set[str] = set()

        for term in terms:
            if isinstance(term, (exp.LT, exp.LTE)):
                column = next(term.this.find_all(exp.Column), None)
                if column is None and isinstance(term.this, exp.Column):
                    column = term.this
                right_sql = term.expression.sql(dialect=dialect).upper()
                if column is not None and "DATE_TRUNC" in right_sql and "MONTH" in right_sql:
                    upper_bounds.add(cls._identifier_key(column.name))
                continue
            if not isinstance(term, (exp.GT, exp.GTE)):
                continue
            column = next(term.this.find_all(exp.Column), None)
            if column is None and isinstance(term.this, exp.Column):
                column = term.this
            if column is None:
                continue
            right_sql = term.expression.sql(dialect=dialect).upper()
            if "DATE_TRUNC" not in right_sql or "MONTH" not in right_sql:
                continue
            intervals = list(term.expression.find_all(exp.Interval))
            if len(intervals) != 1:
                continue
            months = cls._interval_months(intervals[0])
            if months is None:
                continue
            candidates.append((intervals[0], months, cls._identifier_key(column.name)))

        valid = [item for item in candidates if item[2] in upper_bounds]
        if len(valid) != 1:
            return None
        interval, months, _ = valid[0]
        return interval, months

    @staticmethod
    def _interval_months(interval: Any) -> int | None:
        unit_expression = interval.args.get("unit")
        unit = str(
            getattr(unit_expression, "name", "")
            or getattr(unit_expression, "this", "")
            or ""
        ).upper()
        raw = str(getattr(interval.this, "this", interval.this) or "").strip()
        if unit:
            if unit not in {"MONTH", "MONTHS", "MON", "MONS"}:
                return None
            try:
                return int(raw)
            except ValueError:
                return None
        parts = raw.upper().split()
        if len(parts) != 2 or parts[1].rstrip("S") != "MONTH":
            return None
        try:
            return int(parts[0])
        except ValueError:
            return None

    @staticmethod
    def _set_interval_months(interval: Any, months: int) -> None:
        from sqlglot import exp

        unit_expression = interval.args.get("unit")
        if unit_expression is not None:
            interval.set("this", exp.Literal.string(str(months)))
            return
        unit = "MONTH" if months == 1 else "MONTHS"
        interval.set("this", exp.Literal.string(f"{months} {unit}"))

    def _add_filter(self, tree: Any, change: SqlChangeRequest) -> bool:
        from sqlglot import exp

        predicate = self._predicate(change)
        select = self._root_select(tree)
        current_where = select.args.get("where")
        if current_where and self._predicate_present(current_where.this, change):
            return False
        condition = predicate if current_where is None else exp.and_(current_where.this, predicate)
        select.set("where", exp.Where(this=condition))
        return True

    def _remove_filter(
        self,
        tree: Any,
        change: SqlChangeRequest,
        *,
        previous: bool = False,
    ) -> bool:
        from sqlglot import exp

        target = (change.previous_target or change.target) if previous else change.target
        value = change.previous_value if previous else change.value
        if not target:
            raise ValueError("remove_filter requiere target")
        select = self._root_select(tree)
        current_where = select.args.get("where")
        if current_where is None:
            return False
        terms = self._flatten_and(current_where.this)
        kept = [
            term
            for term in terms
            if not self._term_matches(term, target, value=value)
        ]
        if len(kept) == len(terms):
            return False
        if not kept:
            select.set("where", None)
        else:
            rebuilt = kept[0]
            for term in kept[1:]:
                rebuilt = exp.and_(rebuilt, term)
            select.set("where", exp.Where(this=rebuilt))
        return True

    def _change_order(self, tree: Any, change: SqlChangeRequest) -> bool:
        from sqlglot import exp

        if not change.target:
            raise ValueError("change_order requiere target")
        select = self._root_select(tree)
        descending = str(change.direction or "desc").lower().endswith("desc")
        ordered = exp.Ordered(this=exp.column(change.target), desc=descending)
        previous = select.args.get("order")
        previous_sql = previous.sql(dialect=self.dialect) if previous else None
        select.set("order", exp.Order(expressions=[ordered]))
        return previous_sql != select.args["order"].sql(dialect=self.dialect)

    def _predicate(self, change: SqlChangeRequest) -> Any:
        from sqlglot import exp

        if not change.target:
            raise ValueError("El filtro requiere target")
        column = exp.column(change.target)
        operator = (change.operator or "=").strip().upper()
        values = list(change.values)
        if change.value is not None and not values:
            values = [change.value]

        if operator in {"IS NULL", "ISNULL"}:
            return exp.Is(this=column, expression=exp.Null())
        if operator in {"IS NOT NULL", "NOT NULL"}:
            return exp.Not(this=exp.Is(this=column, expression=exp.Null()))
        if operator in {"IN", "NOT IN"}:
            if not values:
                raise ValueError(f"{operator} requiere values")
            expression = exp.In(this=column, expressions=[self._literal(value) for value in values])
            return exp.Not(this=expression) if operator == "NOT IN" else expression
        if operator in {"BETWEEN", "NOT BETWEEN"}:
            if len(values) != 2:
                raise ValueError(f"{operator} requiere dos valores")
            expression = exp.Between(
                this=column,
                low=self._literal(values[0]),
                high=self._literal(values[1]),
            )
            return exp.Not(this=expression) if operator == "NOT BETWEEN" else expression
        if not values:
            raise ValueError(f"{operator} requiere value")
        right = self._literal(values[0])
        operators = {
            "=": exp.EQ,
            "==": exp.EQ,
            "!=": exp.NEQ,
            "<>": exp.NEQ,
            ">": exp.GT,
            ">=": exp.GTE,
            "<": exp.LT,
            "<=": exp.LTE,
            "LIKE": exp.Like,
            "ILIKE": exp.ILike,
        }
        expression_type = operators.get(operator)
        if expression_type is None:
            raise ValueError(f"Operador no soportado de forma determinística: {operator}")
        return expression_type(this=column, expression=right)

    @staticmethod
    def _literal(value: str) -> Any:
        from sqlglot import exp

        raw = str(value).strip()
        if raw.lower() == "null":
            return exp.Null()
        if raw.lower() in {"true", "false"}:
            return exp.Boolean(this=raw.lower() == "true")
        try:
            Decimal(raw)
        except InvalidOperation:
            pass
        else:
            return exp.Literal.number(raw)
        return exp.Literal.string(raw)

    def _predicate_present(self, expression: Any, change: SqlChangeRequest) -> bool:
        return any(
            self._term_matches(term, change.target or "", value=change.value, values=change.values)
            for term in self._flatten_and(expression)
        )

    def _term_matches(
        self,
        term: Any,
        target: str,
        *,
        value: str | None = None,
        values: Iterable[str] | None = None,
    ) -> bool:
        from sqlglot import exp

        target_key = self._identifier_key(target)
        columns = [self._identifier_key(column.name) for column in term.find_all(exp.Column)]
        if target_key not in columns:
            return False
        expected_values = {str(item).strip(" '\"").lower() for item in (values or [])}
        if value is not None:
            expected_values.add(str(value).strip(" '\"").lower())
        if not expected_values:
            return True
        actual_values: set[str] = set()
        for literal in term.find_all(exp.Literal):
            actual_values.add(str(literal.this).strip(" '\"").lower())
        return bool(expected_values & actual_values)

    @staticmethod
    def _flatten_and(expression: Any) -> list[Any]:
        from sqlglot import exp

        if isinstance(expression, exp.And):
            return (
                SqlFeedbackApplier._flatten_and(expression.this)
                + SqlFeedbackApplier._flatten_and(expression.expression)
            )
        return [expression]

    @staticmethod
    def _root_select(tree: Any) -> Any:
        from sqlglot import exp

        if isinstance(tree, exp.Select):
            return tree
        select = tree.find(exp.Select)
        if select is None:
            raise ValueError("La consulta no contiene un SELECT transformable")
        return select

    @classmethod
    def _coerce_plan(
        cls,
        feedback_or_plan: str | SqlFeedbackPlan | dict[str, Any] | None,
    ) -> SqlFeedbackPlan | None:
        if feedback_or_plan is None:
            return None
        if isinstance(feedback_or_plan, SqlFeedbackPlan):
            return feedback_or_plan
        if isinstance(feedback_or_plan, dict):
            return SqlFeedbackPlan.model_validate(feedback_or_plan)
        # Natural language is interpreted by SqlEngineerAgent before this tool is called.
        return SqlFeedbackPlan(
            feedback=feedback_or_plan,
            summary="El texto requiere interpretación mediante el contrato del SQL Engineer.",
            strategy=SqlFeedbackStrategy.REGENERATE,
            changes=[],
            requires_regeneration=True,
        )

    @staticmethod
    def _read_limit(tree: Any) -> int | None:
        from sqlglot import exp

        limit = tree.args.get("limit")
        expression = limit.args.get("expression") if limit is not None else None
        if isinstance(expression, exp.Literal) and expression.is_int:
            return int(expression.this)
        return None

    @staticmethod
    def _parse_positive_int(value: str) -> int | None:
        normalized = str(value).strip().replace("_", "").replace(",", "")
        try:
            parsed = int(normalized)
        except ValueError:
            return None
        return parsed if parsed > 0 else None

    @staticmethod
    def _identifier_key(value: str) -> str:
        return value.split(".")[-1].strip('"').lower()
