from __future__ import annotations

import re
from typing import Any, Iterable

from axiz.pe.sql_agent.models.contracts import (
    SqlChangeRequest,
    SqlChangeType,
    SqlFeedbackApplication,
    SqlFeedbackPlan,
    SqlFeedbackStrategy,
)


class SqlFeedbackApplier:
    """Apply safe structural portions of a semantic HITL feedback plan to SQL AST.

    Semantic changes are still regenerated by the SQL agent. This tool then enforces structural
    postconditions that can be applied without guessing business meaning: limits, simple filters
    and ordering. More complex requests are marked as deferred and verified by the compliance
    stage against the regenerated SQL.
    """

    _LIMIT_PATTERNS = (
        re.compile(
            r"(?ix)\b(?:sube|aumenta|incrementa|cambia|ajusta|pon|establece|modifica|reduce|baja)"
            r"[^\n]{0,45}?\b(?:el\s+)?l[ií]mite\b[^\d]{0,15}(\d[\d._,]*)"
        ),
        re.compile(
            r"(?ix)\b(?:l[ií]mite|limit|max(?:imo)?|m[aá]ximo|top)\b"
            r"\s*(?:de|a|en|=|:)?\s*(\d[\d._,]*)\b"
        ),
        re.compile(
            r"(?ix)\b(?:muestra|devuelve|retorna|trae|obt[eé]n)\b[^\n]{0,30}?"
            r"(\d[\d._,]*)\s+(?:filas|registros|resultados)\b"
        ),
        re.compile(
            r"(?ix)\b(\d[\d._,]*)\s+(?:filas|registros|resultados)\s+como\s+m[aá]ximo\b"
        ),
    )

    _INTERPRETATION_LIMIT_PATTERNS = (
        re.compile(r"(?i)\blimitad[oa]s?\s+a\s+\d[\d._,]*\s+(?:resultados|filas|registros)\b"),
        re.compile(r"(?i)\b(?:hasta|m[aá]ximo\s+de)\s+\d[\d._,]*\s+(?:resultados|filas|registros)\b"),
        re.compile(r"(?i)\btop\s+\d[\d._,]*\b"),
    )

    _DETERMINISTIC_TYPES = {
        SqlChangeType.SET_LIMIT,
        SqlChangeType.ADD_FILTER,
        SqlChangeType.REMOVE_FILTER,
        SqlChangeType.REPLACE_FILTER,
        SqlChangeType.CHANGE_ORDER,
    }

    def __init__(self, dialect: str, max_rows: int) -> None:
        self.dialect = dialect
        self.max_rows = max_rows

    def apply(
        self,
        sql: str,
        feedback_or_plan: str | SqlFeedbackPlan | dict[str, Any] | None,
        *,
        previous_sql: str | None = None,
    ) -> SqlFeedbackApplication:
        plan = self._coerce_plan(feedback_or_plan)
        if not plan or not plan.changes:
            return SqlFeedbackApplication(sql=sql.strip().rstrip(";"))

        import sqlglot

        try:
            tree = sqlglot.parse_one(sql, read=self.dialect)
        except sqlglot.errors.ParseError as exc:
            return SqlFeedbackApplication(
                sql=sql.strip().rstrip(";"),
                failed_changes=[change.change_id for change in plan.changes],
                warnings=[f"No se pudo aplicar el feedback sobre el AST: {exc}"],
            )

        application = SqlFeedbackApplication(sql=sql.strip().rstrip(";"))
        if previous_sql:
            try:
                previous_tree = sqlglot.parse_one(previous_sql, read=self.dialect)
                self._preserve_unrequested_invariants(
                    previous_tree,
                    tree,
                    plan,
                    application,
                )
            except sqlglot.errors.ParseError as exc:
                application.warnings.append(
                    f"No se pudo preservar el contrato SQL anterior: {exc}"
                )
        for change in plan.changes:
            if change.change_type not in self._DETERMINISTIC_TYPES:
                application.deferred_changes.append(change.change_id)
                continue
            try:
                changed = self._apply_change(tree, change, application)
            except (TypeError, ValueError) as exc:
                application.failed_changes.append(change.change_id)
                application.warnings.append(
                    f"No se pudo aplicar {change.change_id} de forma determinística: {exc}"
                )
                continue
            if changed:
                application.applied_changes.append(change.change_id)
                application.changed = True
            else:
                # The regenerated SQL may already contain the requested state. Compliance will
                # verify it, so this is not considered a failure.
                application.deferred_changes.append(change.change_id)

        application.sql = tree.sql(dialect=self.dialect, pretty=True)
        return application

    def _preserve_unrequested_invariants(
        self,
        previous_tree: Any,
        revised_tree: Any,
        plan: SqlFeedbackPlan,
        application: SqlFeedbackApplication,
    ) -> None:
        """Restore clauses that the user did not request to modify.

        This is intentionally deterministic. A semantic follow-up may regenerate SQL, but it
        must not reset a previously approved LIMIT, ORDER BY, filter, grouping or projection just
        because the generator used a default/example query.
        """
        from sqlglot import exp

        change_types = {change.change_type for change in plan.changes}
        if SqlChangeType.SEMANTIC_REGENERATION in change_types:
            return

        previous_select = self._root_select(previous_tree)
        revised_select = self._root_select(revised_tree)

        if SqlChangeType.SET_LIMIT not in change_types:
            self._preserve_arg(
                previous_tree,
                revised_tree,
                "limit",
                "limit",
                application,
            )

        if SqlChangeType.CHANGE_ORDER not in change_types:
            self._preserve_arg(
                previous_select,
                revised_select,
                "order",
                "ordering",
                application,
            )

        filter_changes = {
            SqlChangeType.ADD_FILTER,
            SqlChangeType.REMOVE_FILTER,
            SqlChangeType.REPLACE_FILTER,
            SqlChangeType.CHANGE_TIME_WINDOW,
        }
        if not (change_types & filter_changes):
            self._preserve_arg(
                previous_select,
                revised_select,
                "where",
                "filters",
                application,
            )

        dimension_changes = {
            SqlChangeType.ADD_DIMENSION,
            SqlChangeType.REMOVE_DIMENSION,
            SqlChangeType.CHANGE_GROUPING,
        }
        if not (change_types & dimension_changes):
            self._preserve_arg(
                previous_select,
                revised_select,
                "group",
                "grouping",
                application,
            )
            self._preserve_arg(
                previous_select,
                revised_select,
                "having",
                "having",
                application,
            )

        semantic_shape_changes = dimension_changes | {
            SqlChangeType.ADD_METRIC,
            SqlChangeType.REMOVE_METRIC,
            SqlChangeType.REPLACE_METRIC,
            SqlChangeType.REPLACE_SOURCE,
        }
        if not (change_types & semantic_shape_changes):
            previous_expressions = previous_select.args.get("expressions") or []
            revised_expressions = revised_select.args.get("expressions") or []
            if self._sql_list(previous_expressions) != self._sql_list(revised_expressions):
                revised_select.set(
                    "expressions",
                    [expression.copy() for expression in previous_expressions],
                )
                application.preserved_invariants.append("projection")

            for key, label in (("from_", "sources"), ("joins", "joins")):
                self._preserve_arg(
                    previous_select,
                    revised_select,
                    key,
                    label,
                    application,
                )

        # Preserve DISTINCT unless the analytical shape explicitly changed.
        if not (change_types & semantic_shape_changes):
            self._preserve_arg(
                previous_select,
                revised_select,
                "distinct",
                "distinct",
                application,
            )

    def _preserve_arg(
        self,
        previous: Any,
        revised: Any,
        key: str,
        label: str,
        application: SqlFeedbackApplication,
    ) -> None:
        previous_value = previous.args.get(key)
        revised_value = revised.args.get(key)
        if self._sql_value(previous_value) == self._sql_value(revised_value):
            return
        if isinstance(previous_value, list):
            revised.set(key, [value.copy() for value in previous_value])
        elif previous_value is None:
            revised.set(key, None)
        else:
            revised.set(key, previous_value.copy())
        application.preserved_invariants.append(label)

    def _sql_value(self, value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, list):
            return "|".join(self._sql_list(value))
        return value.sql(dialect=self.dialect).strip().lower()

    def _sql_list(self, values: Iterable[Any]) -> list[str]:
        return [value.sql(dialect=self.dialect).strip().lower() for value in values]

    def reconcile_interpretation(
        self,
        interpretation: str,
        application: SqlFeedbackApplication,
    ) -> str:
        if application.applied_limit is None:
            return interpretation
        replacement = f"con un máximo de {application.applied_limit} resultados"
        for pattern in self._INTERPRETATION_LIMIT_PATTERNS:
            if pattern.search(interpretation):
                return pattern.sub(replacement, interpretation, count=1)
        return (
            interpretation.rstrip().rstrip(".")
            + f". La consulta devuelve como máximo {application.applied_limit} resultados."
        )

    def reconcile_filters(
        self,
        filters: list[dict[str, Any]],
        plan: SqlFeedbackPlan | None,
    ) -> list[dict[str, Any]]:
        if not plan:
            return list(filters)
        current = [dict(item) for item in filters]
        for change in plan.changes:
            target = self._identifier_key(change.target or "")
            if change.change_type == SqlChangeType.REMOVE_FILTER:
                current = [
                    item for item in current
                    if self._identifier_key(str(item.get("field", ""))) != target
                ]
            elif change.change_type == SqlChangeType.REPLACE_FILTER:
                previous = self._identifier_key(change.previous_target or change.target or "")
                current = [
                    item for item in current
                    if self._identifier_key(str(item.get("field", ""))) != previous
                ]
                if change.target:
                    current.append(self._filter_contract(change))
            elif change.change_type == SqlChangeType.ADD_FILTER and change.target:
                candidate = self._filter_contract(change)
                if candidate not in current:
                    current.append(candidate)
        return current

    @staticmethod
    def _filter_contract(change: SqlChangeRequest) -> dict[str, Any]:
        value = change.value
        if change.values:
            value = ", ".join(change.values)
        return {
            "field": change.target or "",
            "operator": change.operator or "=",
            "value": value or "",
            "source": "human_feedback",
        }

    def _apply_change(
        self,
        tree: Any,
        change: SqlChangeRequest,
        application: SqlFeedbackApplication,
    ) -> bool:
        if change.change_type == SqlChangeType.SET_LIMIT:
            return self._set_limit(tree, change, application)
        if change.change_type == SqlChangeType.ADD_FILTER:
            return self._add_filter(tree, change)
        if change.change_type == SqlChangeType.REMOVE_FILTER:
            return self._remove_filter(tree, change)
        if change.change_type == SqlChangeType.REPLACE_FILTER:
            removed = self._remove_filter(tree, change, previous=True)
            added = self._add_filter(tree, change)
            return removed or added
        if change.change_type == SqlChangeType.CHANGE_ORDER:
            return self._change_order(tree, change)
        return False

    def _set_limit(
        self,
        tree: Any,
        change: SqlChangeRequest,
        application: SqlFeedbackApplication,
    ) -> bool:
        from sqlglot import exp

        requested = change.limit
        if requested is None and change.value:
            requested = self._parse_positive_int(change.value)
        if requested is None:
            raise ValueError("set_limit requiere limit o value numérico")
        applied = min(requested, self.max_rows)
        previous = self._read_limit(tree)
        tree.set("limit", exp.Limit(expression=exp.Literal.number(applied)))
        application.requested_limit = requested
        application.applied_limit = applied
        application.previous_limit = previous
        if requested > self.max_rows:
            application.warnings.append(
                f"El límite solicitado ({requested}) supera MAX_RESULT_ROWS={self.max_rows}; "
                f"se aplicó {applied}."
            )
        return previous != applied

    def _add_filter(self, tree: Any, change: SqlChangeRequest) -> bool:
        from sqlglot import exp

        predicate = self._predicate(change)
        select = self._root_select(tree)
        current_where = select.args.get("where")
        if current_where and self._predicate_present(current_where.this, change):
            return False
        condition = predicate if current_where is None else exp.and_(current_where.this, predicate)
        select.set("where", exp.Where(this=condition))
        return True

    def _remove_filter(
        self,
        tree: Any,
        change: SqlChangeRequest,
        *,
        previous: bool = False,
    ) -> bool:
        from sqlglot import exp

        target = (change.previous_target or change.target) if previous else change.target
        value = change.previous_value if previous else change.value
        if not target:
            raise ValueError("remove_filter requiere target")
        select = self._root_select(tree)
        current_where = select.args.get("where")
        if current_where is None:
            return False
        terms = self._flatten_and(current_where.this)
        kept = [
            term
            for term in terms
            if not self._term_matches(term, target, value=value)
        ]
        if len(kept) == len(terms):
            return False
        if not kept:
            select.set("where", None)
        else:
            rebuilt = kept[0]
            for term in kept[1:]:
                rebuilt = exp.and_(rebuilt, term)
            select.set("where", exp.Where(this=rebuilt))
        return True

    def _change_order(self, tree: Any, change: SqlChangeRequest) -> bool:
        from sqlglot import exp

        if not change.target:
            raise ValueError("change_order requiere target")
        select = self._root_select(tree)
        descending = str(change.direction or "desc").lower().endswith("desc")
        ordered = exp.Ordered(this=exp.column(change.target), desc=descending)
        previous = select.args.get("order")
        previous_sql = previous.sql(dialect=self.dialect) if previous else None
        select.set("order", exp.Order(expressions=[ordered]))
        return previous_sql != select.args["order"].sql(dialect=self.dialect)

    def _predicate(self, change: SqlChangeRequest) -> Any:
        from sqlglot import exp

        if not change.target:
            raise ValueError("El filtro requiere target")
        column = exp.column(change.target)
        operator = (change.operator or "=").strip().upper()
        values = list(change.values)
        if change.value is not None and not values:
            values = [change.value]

        if operator in {"IS NULL", "ISNULL"}:
            return exp.Is(this=column, expression=exp.Null())
        if operator in {"IS NOT NULL", "NOT NULL"}:
            return exp.Not(this=exp.Is(this=column, expression=exp.Null()))
        if operator in {"IN", "NOT IN"}:
            if not values:
                raise ValueError(f"{operator} requiere values")
            expression = exp.In(this=column, expressions=[self._literal(value) for value in values])
            return exp.Not(this=expression) if operator == "NOT IN" else expression
        if operator in {"BETWEEN", "NOT BETWEEN"}:
            if len(values) != 2:
                raise ValueError(f"{operator} requiere dos valores")
            expression = exp.Between(
                this=column,
                low=self._literal(values[0]),
                high=self._literal(values[1]),
            )
            return exp.Not(this=expression) if operator == "NOT BETWEEN" else expression
        if not values:
            raise ValueError(f"{operator} requiere value")
        right = self._literal(values[0])
        operators = {
            "=": exp.EQ,
            "==": exp.EQ,
            "!=": exp.NEQ,
            "<>": exp.NEQ,
            ">": exp.GT,
            ">=": exp.GTE,
            "<": exp.LT,
            "<=": exp.LTE,
            "LIKE": exp.Like,
            "ILIKE": exp.ILike,
        }
        expression_type = operators.get(operator)
        if expression_type is None:
            raise ValueError(f"Operador no soportado de forma determinística: {operator}")
        return expression_type(this=column, expression=right)

    @staticmethod
    def _literal(value: str) -> Any:
        from sqlglot import exp

        raw = str(value).strip()
        if raw.lower() == "null":
            return exp.Null()
        if raw.lower() in {"true", "false"}:
            return exp.Boolean(this=raw.lower() == "true")
        if re.fullmatch(r"[-+]?\d+(?:\.\d+)?", raw):
            return exp.Literal.number(raw)
        return exp.Literal.string(raw)

    def _predicate_present(self, expression: Any, change: SqlChangeRequest) -> bool:
        return any(
            self._term_matches(term, change.target or "", value=change.value, values=change.values)
            for term in self._flatten_and(expression)
        )

    def _term_matches(
        self,
        term: Any,
        target: str,
        *,
        value: str | None = None,
        values: Iterable[str] | None = None,
    ) -> bool:
        from sqlglot import exp

        target_key = self._identifier_key(target)
        columns = [self._identifier_key(column.name) for column in term.find_all(exp.Column)]
        if target_key not in columns:
            return False
        expected_values = {str(item).strip(" '\"").lower() for item in (values or [])}
        if value is not None:
            expected_values.add(str(value).strip(" '\"").lower())
        if not expected_values:
            return True
        actual_values: set[str] = set()
        for literal in term.find_all(exp.Literal):
            actual_values.add(str(literal.this).strip(" '\"").lower())
        return bool(expected_values & actual_values)

    @staticmethod
    def _flatten_and(expression: Any) -> list[Any]:
        from sqlglot import exp

        if isinstance(expression, exp.And):
            return (
                SqlFeedbackApplier._flatten_and(expression.this)
                + SqlFeedbackApplier._flatten_and(expression.expression)
            )
        return [expression]

    @staticmethod
    def _root_select(tree: Any) -> Any:
        from sqlglot import exp

        if isinstance(tree, exp.Select):
            return tree
        select = tree.find(exp.Select)
        if select is None:
            raise ValueError("La consulta no contiene un SELECT transformable")
        return select

    @classmethod
    def _coerce_plan(
        cls,
        feedback_or_plan: str | SqlFeedbackPlan | dict[str, Any] | None,
    ) -> SqlFeedbackPlan | None:
        if feedback_or_plan is None:
            return None
        if isinstance(feedback_or_plan, SqlFeedbackPlan):
            return feedback_or_plan
        if isinstance(feedback_or_plan, dict):
            return SqlFeedbackPlan.model_validate(feedback_or_plan)
        requested = cls.extract_requested_limit(feedback_or_plan)
        if requested is None:
            return SqlFeedbackPlan(
                feedback=feedback_or_plan,
                summary="Feedback sin transformación determinística conocida.",
                strategy=SqlFeedbackStrategy.REGENERATE,
                changes=[],
                requires_regeneration=True,
            )
        return SqlFeedbackPlan(
            feedback=feedback_or_plan,
            summary=f"Cambiar el límite a {requested}.",
            strategy=SqlFeedbackStrategy.AST_ONLY,
            requires_regeneration=False,
            changes=[
                SqlChangeRequest(
                    change_id="change_1",
                    change_type=SqlChangeType.SET_LIMIT,
                    limit=requested,
                    deterministic_candidate=True,
                )
            ],
        )

    @classmethod
    def extract_requested_limit(cls, feedback: str | None) -> int | None:
        if not feedback:
            return None
        for pattern in cls._LIMIT_PATTERNS:
            match = pattern.search(feedback)
            if match:
                value = re.sub(r"[^0-9]", "", match.group(1))
                if value:
                    parsed = int(value)
                    return parsed if parsed > 0 else None
        return None

    @staticmethod
    def _read_limit(tree: Any) -> int | None:
        from sqlglot import exp

        limit = tree.args.get("limit")
        expression = limit.args.get("expression") if limit is not None else None
        if isinstance(expression, exp.Literal) and expression.is_int:
            return int(expression.this)
        return None

    @staticmethod
    def _parse_positive_int(value: str) -> int | None:
        digits = re.sub(r"[^0-9]", "", value)
        parsed = int(digits) if digits else 0
        return parsed if parsed > 0 else None

    @staticmethod
    def _identifier_key(value: str) -> str:
        return value.split(".")[-1].strip('"').lower()
